Document: libgit2
Title: Debian libgit2 Manual
Author: <insert document author here>
Abstract: This manual describes what libgit2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libgit2/libgit2.sgml.gz

Format: postscript
Files: /usr/share/doc/libgit2/libgit2.ps.gz

Format: text
Files: /usr/share/doc/libgit2/libgit2.text.gz

Format: HTML
Index: /usr/share/doc/libgit2/html/index.html
Files: /usr/share/doc/libgit2/html/*.html
